---
abstract: 'A Streaming Text Orientated Messaging Protocol Client'
author:
  - 'Leon Brocard <acme@astray.com>,'
  - 'Thom May <thom.may@betfair.com>,'
  - 'Michael S. Fischer <michael@dynamine.net>,'
  - 'Ash Berlin <ash_github@firemirror.com>'
build_requires:
  Test::Fatal: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Stomp
provides:
  Net::Stomp:
    file: lib/Net/Stomp.pm
    version: '0.47'
  Net::Stomp::Frame:
    file: lib/Net/Stomp/Frame.pm
    version: '0.47'
recommends:
  IO::Socket::IP: '0.20'
  IO::Socket::SSL: '1.75'
requires:
  Class::Accessor::Fast: '0'
  IO::Select: '0'
  IO::Socket::INET: '0'
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/dakkar/net-stomp.git
version: '0.47'
