---
abstract: 'A Streaming Text Orientated Messaging Protocol Client'
author:
  - "Leon Brocard <acme@astray.com>.\nThom May <thom.may@betfair.com>.\nAsh Berlin <ash_github@firemirror.com>."
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Stomp
provides:
  Net::Stomp:
    file: lib/Net/Stomp.pm
    version: 0.35
  Net::Stomp::Frame:
    file: lib/Net/Stomp/Frame.pm
requires:
  Class::Accessor::Fast: 0
  IO::Select: 0
  IO::Socket::INET: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.35
